--- caps ---
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Secretaria')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Médico Generalista')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Enfermero')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Trabajador Social')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Psicologo')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Nutricionista')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Obstetra')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Terapista Ocupacional')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Maestranza')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Odontólogo')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Atención temprana del desarrollo')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'ESI')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Pediatra')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Psicologo infantil')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Administración')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Ginecóloga')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Fonoaudiologa')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Psicopedagoga')
INSERT INTO `prestaciones`(`id_prestaciones`, `nombre`) VALUES (NULL,'Desarrollo infantil y Lactancia')
